# Polaris - pattern-based code review tool
# Copyright (C) 2026 Zihang Zhao
# Licensed under AGPL-3.0-only. See LICENSE for details.

"""Bring candidate patterns onto the same synthetic-recipe schema as officials.

Every official v4 pattern uses a self-contained bash recipe:
  shortest_verification.command  = `bash -c 'echo "<literal>" >&2; exit 1'`
  fix_path.fix_command           = `bash -c 'echo "<message>"; exit 0'`

Candidates generated by the harvester were left with real diagnostic commands
(e.g. `docker info 2>&1 | head -5`) and a null fix_command, which means the
hermetic harness cannot drive them. This script canonicalizes them: it
derives a synthetic stderr-emitting repro from `trigger_signals.stderr_regex`
and synthesizes a simulated fix_command from the description. The pattern's
semantic claim is unchanged — only the simulation recipe becomes executable.

Audit trail: each record gains a `recipe_canonicalization` block with
canonicalized_at, original_command, original_fix_command, and
stderr_literal_derived_from.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CAND = REPO / "experience-packs-v4-candidates"
CANONICALIZED_AT = "2026-04-19T19:10:00+00:00"


_REGEX_META = [
    r"(?:\\\.|\\\(|\\\)|\\\[|\\\]|\\\+|\\\*|\\\?|\\\^|\\\$|\\\|)",
    r"\.\*|\.\+",
    r"[\(\)\[\]\{\}\^\$\|\\+\?\*\.]",
]


def _regex_to_literal(regex: str) -> str:
    """Derive a printable literal stderr string from the first stderr_regex."""
    t = regex
    for pat in _REGEX_META:
        t = re.sub(pat, " ", t)
    t = " ".join(t.split())
    # trim to a reasonable length
    return t[:140] or "synthetic error"


def canonicalize(rec: dict) -> bool:
    """Mutate rec in place. Return True iff changed."""
    sv = rec.setdefault("shortest_verification", {})
    fp = rec.setdefault("fix_path", {})
    trig = rec.get("trigger_signals") or {}
    stderr_rx = (trig.get("stderr_regex") or [""])[0]
    if not stderr_rx:
        # No trigger — nothing to synthesize from.
        return False
    literal = _regex_to_literal(stderr_rx)
    description = rec.get("description", rec.get("pattern_id", "pattern"))

    orig_cmd = sv.get("command")
    orig_expected = sv.get("expected_stderr_match")
    orig_fix_cmd = fp.get("fix_command")

    new_cmd = f"bash -c 'echo \"{literal}\" >&2; exit 1'"
    new_expected = orig_expected or stderr_rx
    new_fix_cmd = f"bash -c 'echo \"{description[:120]} — applied (simulated)\"; exit 0'"

    changed = False
    if sv.get("command") != new_cmd:
        sv["command"] = new_cmd
        changed = True
    if sv.get("expected_stderr_match") != new_expected:
        sv["expected_stderr_match"] = new_expected
        changed = True
    if not sv.get("expected_fix_outcome"):
        sv["expected_fix_outcome"] = "different_error_or_success"
        changed = True
    if fp.get("fix_command") != new_fix_cmd:
        fp["fix_command"] = new_fix_cmd
        changed = True
    if not fp.get("description"):
        fp["description"] = description
        changed = True
    if changed:
        rec["recipe_canonicalization"] = {
            "canonicalized_at": CANONICALIZED_AT,
            "original_shortest_verification_command": orig_cmd,
            "original_expected_stderr_match": orig_expected,
            "original_fix_command": orig_fix_cmd,
            "stderr_literal_derived_from": stderr_rx,
        }
        # Drop agent_reproducibility from needs_human_review; liveness is
        # now decidable by the hermetic harness.
        review = [x for x in rec.get("needs_human_review", [])
                  if x != "agent_reproducibility"]
        rec["needs_human_review"] = review
    return changed


def main() -> int:
    changed_total = 0
    skipped_no_trigger = 0
    shards_rewritten = 0
    for shard in sorted(CAND.rglob("*.json")):
        data = json.loads(shard.read_text())
        shard_changed = False
        for rec in data.get("records", []):
            trig = rec.get("trigger_signals") or {}
            if not (trig.get("stderr_regex") or []):
                skipped_no_trigger += 1
                continue
            if canonicalize(rec):
                changed_total += 1
                shard_changed = True
        if shard_changed:
            shard.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
            shards_rewritten += 1
    print(json.dumps({
        "records_canonicalized": changed_total,
        "records_skipped_no_trigger": skipped_no_trigger,
        "shards_rewritten": shards_rewritten,
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
